steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/algebraic-creek-429005-h2/images/my-python-web', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-east1-docker.pkg.dev/algebraic-creek-429005-h2/images/my-python-web']
images: ['asia-east1-docker.pkg.dev/algebraic-creek-429005-h2/images/my-python-web']
options:
  logging: CLOUD_LOGGING_ONLY